export const RESTAURANT_LOGIN_REQUEST = 'RESTAURANT_LOGIN_REQUEST';
export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS';
export const RESTAURANT_LOGIN_FAIL = 'RESTAURANT_LOGIN_FAIL';

export const RESTAURANT_LOGOUT_REQUEST = 'RESTAURANT_LOGOUT_REQUEST';
export const RESTAURANT_LOGOUT_SUCCESS = 'RESTAURANT_LOGOUT_SUCCESS';
export const RESTAURANT_LOGOUT_FAIL = 'RESTAURANT_LOGOUT_FAIL';

export const RESTAURANT_REGISTER_REQUEST = 'RESTAURANT_REGISTER_REQUEST';
export const RESTAURANT_REGISTER_SUCCESS = 'RESTAURANT_REGISTER_SUCCESS';
export const RESTAURANT_REGISTER_FAIL = 'RESTAURANT_REGISTER_FAIL';

