export const CUSTOMER_LOGIN_REQUEST = 'LOGIN_REQUEST';
export const CUSTOMER_LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CUSTOMER_LOGIN_FAIL = 'LOGIN_FAIL';

export const CUSTOMER_LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const CUSTOMER_LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const CUSTOMER_LOGOUT_FAIL = 'LOGOUT_FAIL';

export const CUSTOMER_REGISTER_REQUEST = 'REGISTER_REQUEST';
export const CUSTOMER_REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const CUSTOMER_REGISTER_FAIL = 'REGISTER_FAIL';
