export const GET_CUS_PROFILE_REQUEST = 'GET_CUS_PROFILE_REQUEST';
export const GET_CUS_PROFILE_SUCCESS = 'GET_CUS_PROFILE_SUCCESS';
export const GET_CUS_PROFILE_FAILURE = 'GET_CUS_PROFILE_FAILURE';

export const UPDATE_CUS_PROFILE_REQUEST = 'UPDATE_CUS_PROFILE_REQUEST';
export const UPDATE_CUS_PROFILE_SUCCESS = 'UPDATE_CUS_PROFILE_SUCCESS';
export const UPDATE_CUS_PROFILE_FAILURE = 'UPDATE_CUS_PROFILE_FAILURE';
