export const CREATE_DISHES_REQUEST = "GET_DISHES_REQUEST";
export const CREATE_DISHES_SUCCESS = "GET_DISHES_SUCCESS";
export const CREATE_DISHES_FAIL = "GET_DISHES_FAIL";

export const GET_ONE_DISH_REQUEST = "GET_ONE_DISH_REQUEST";
export const GET_ONE_DISH_SUCCESS = "GET_ONE_DISH_SUCCESS";
export const GET_ONE_DISH_FAIL = "GET_ONE_DISH_FAIL";

export const UPDATE_DISHES_REQUEST = "UPDATE_DISHES_REQUEST";
export const UPDATE_DISHES_SUCCESS = "UPDATE_DISHES_SUCCESS";
export const UPDATE_DISHES_FAIL = "UPDATE_DISHES_FAIL";

export const DELETE_DISHES_REQUEST = "DELETE_DISHES_REQUEST";
export const DELETE_DISHES_SUCCESS = "DELETE_DISHES_SUCCESS";
export const DELETE_DISHES_FAIL = "DELETE_DISHES_FAIL";