export const FAVORITE_LIST_REQUEST = "FAVORITE_LIST_REQUEST";
export const FAVORITE_LIST_SUCCESS = "FAVORITE_LIST_SUCCESS";
export const FAVORITE_LIST_FAIL = "FAVORITE_LIST_FAIL";

export const FAVORITE_ADD_REQUEST = "FAVORITE_ADD_REQUEST";
export const FAVORITE_ADD_SUCCESS = "FAVORITE_ADD_SUCCESS";
export const FAVORITE_ADD_FAIL = "FAVORITE_ADD_FAIL";

export const FAVORITE_REMOVE_REQUEST = "FAVORITE_REMOVE_REQUEST";
export const FAVORITE_REMOVE_SUCCESS = "FAVORITE_REMOVE_SUCCESS";
export const FAVORITE_REMOVE_FAIL = "FAVORITE_REMOVE_FAIL";

