export const GET_CUS_ORDER_REQUEST = 'GET_CUS_ORDER_REQUEST';
export const GET_CUS_ORDER_SUCCESS = 'GET_CUS_ORDER_SUCCESS';
export const GET_CUS_ORDER_FAILURE = 'GET_CUS_ORDER_FAILURE';

export const GET_RES_ORDER_REQUEST = 'GET_RES_ORDER_REQUEST';
export const GET_RES_ORDER_SUCCESS = 'GET_RES_ORDER_SUCCESS';
export const GET_RES_ORDER_FAILURE = 'GET_RES_ORDER_FAILURE';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE';

