export const RESTAURANT_LIST_REQUEST = "RESTAURANT_LIST_REQUEST";
export const RESTAURANT_LIST_SUCCESS = "RESTAURANT_LIST_SUCCESS";
export const RESTAURANT_LIST_FAIL = "RESTAURANT_LIST_FAIL";

export const REST_DISHES_LIST_REQUEST = "REST_DISHES_LIST_REQUEST";
export const REST_DISHES_LIST_SUCCESS = "REST_DISHES_LIST_SUCCESS";
export const REST_DISHES_LIST_FAIL = "REST_DISHES_LIST_FAIL";