export const GET_REST_PROFILE_REQUEST = 'GET_REST_PROFILE_REQUEST';
export const GET_REST_PROFILE_SUCCESS = 'GET_REST_PROFILE_SUCCESS';
export const GET_REST_PROFILE_FAILURE = 'GET_REST_PROFILE_FAILURE';

export const GET_MY_REST_PROFILE_REQUEST = 'GET_MY_REST_PROFILE_REQUEST';
export const GET_MY_REST_PROFILE_SUCCESS = 'GET_MY_REST_PROFILE_SUCCESS';
export const GET_MY_REST_PROFILE_FAILURE = 'GET_MY_REST_PROFILE_FAILURE';

export const GET_FAVORITE_REST_PROFILE_REQUEST = 'GET_FAVORITE_REST_PROFILE_REQUEST';
export const GET_FAVORITE_REST_PROFILE_SUCCESS = 'GET_FAVORITE_REST_PROFILE_SUCCESS';
export const GET_FAVORITE_REST_PROFILE_FAILURE = 'GET_FAVORITE_REST_PROFILE_FAILURE';

export const UPDATE_REST_PROFILE_REQUEST = 'UPDATE_REST_PROFILE_REQUEST';
export const UPDATE_REST_PROFILE_SUCCESS = 'UPDATE_REST_PROFILE_SUCCESS';
export const UPDATE_REST_PROFILE_FAILURE = 'UPDATE_REST_PROFILE_FAILURE';
