apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 982081080014.dkr.ecr.us-east-2.amazonaws.com/order-service:latest
          ports:
            - containerPort: 5003
          env:
            - name: MONGO_URI
              value: "mongodb+srv://nairuiliu:018213234Sh12%4095@clusterlab2.o3pwqmp.mongodb.net/?retryWrites=true&w=majority&appName=ClusterLab2"
            - name: JWT_SECRET
              value: "your_jwt_secret_key"
            - name: KAFKA_BROKER
              value: "kafka.default.svc.cluster.local:9092"
